require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
end

target 'App' do
  capacitor_pods
  # Native WebRTC (LiveKit-maintained prebuilt) for the PinecallCall plugin
  pod 'WebRTC-SDK', '~> 125.6422.07'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
